---
# configure hostname and hosts file

- name: update /etc/hosts
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} OPENBAO HOSTS"
    block: |
      #jinja2: trim_blocks:False
      {%- for count in range(cluster_size) %}
      {{ openbao_data.server[count].instance.ip_priv1 }} {{ openbao_data.server[count].instance.hostname }}
      {%- endfor %}

- name: configure hostnames
  hostname:
    use: systemd
    name: "{{ openbao_data.server[count].instance.hostname }}"
  run_once: true
  delegate_to: "{{ item }}"
  loop: "{{ groups['openbao'] }}"
  loop_control:
    index_var: count