---
# set app specific ufw rules 
- name: Allow public access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow private cluster access to tcp port 8200
  community.general.ufw:
    rule: allow
    port: '8200'
    proto: tcp
    from_ip: "{{ item.instance.ip_priv1 }}"
  loop: "{{ openbao_data.server }}"

- name: Allow private cluster access to tcp port 8201
  community.general.ufw:
    rule: allow
    port: '8201'
    proto: tcp
    from_ip: "{{ item.instance.ip_priv1 }}"
  loop: "{{ openbao_data.server }}"

# async to avoid connection disruption
- name: Enable ufw
  community.general.ufw:
    state: enabled
  async: 60
  poll: 0